# Generated by Django 5.0.2 on 2024-02-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Country1', models.CharField(max_length=100)),
                ('Country2', models.CharField(max_length=100)),
            ],
        ),
    ]
