# Generated by Django 5.0.2 on 2024-02-29 01:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plan_trajectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='traject',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
