# Generated by Django 5.0.2 on 2024-02-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('ville', models.CharField(max_length=255)),
            ],
        ),
    ]
