# Generated by Django 5.0.2 on 2024-02-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_plan_trajectid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='trajectId',
            new_name='traject',
        ),
    ]
