# Generated by Django 5.0.2 on 2024-02-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_country1_match_country1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='City',
            new_name='city',
        ),
        migrations.AddField(
            model_name='guider',
            name='avatar',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='guider',
            name='description',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
