# Generated by Django 5.0.2 on 2024-02-29 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_trajectid_plan_traject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='traject',
        ),
    ]
