# Generated by Django 5.0.2 on 2024-02-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_city_match_city_guider_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
