# Generated by Django 5.0.2 on 2024-02-29 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_plan_traject'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='traject_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.traject'),
        ),
    ]
