# Generated by Django 5.0.2 on 2024-02-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guider',
            name='description',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
