# Generated by Django 5.0.2 on 2024-03-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_plan_traject_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('picture', models.CharField(max_length=255)),
                ('transportType', models.CharField(max_length=1000)),
            ],
        ),
    ]
