# Generated by Django 5.0.2 on 2024-03-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_depart', models.CharField(max_length=255)),
                ('ville_arrivee', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
